BEGIN;

CREATE TABLE IF NOT EXISTS sertifikat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL
        REFERENCES users(id) ON DELETE RESTRICT,

    nama VARCHAR(200) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    jenis VARCHAR(100),
    penerbit VARCHAR(200) NOT NULL,
    nomor_sertifikat VARCHAR(150),
    tanggal_terbit DATE,
    tanggal_kedaluwarsa DATE,

    deskripsi TEXT,
    tautan TEXT,
    file_path TEXT NOT NULL,

    status_verifikasi VARCHAR(30) NOT NULL
        DEFAULT 'belum_terverifikasi',
    catatan_verifikasi TEXT,
    diverifikasi_oleh BIGINT
        REFERENCES users(id) ON DELETE RESTRICT,
    diverifikasi_pada TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT sertifikat_status_verifikasi_check
        CHECK (
            status_verifikasi IN (
                'belum_terverifikasi',
                'dalam_peninjauan',
                'terverifikasi',
                'ditolak'
            )
        ),

    CONSTRAINT sertifikat_tanggal_check
        CHECK (
            tanggal_kedaluwarsa IS NULL
            OR tanggal_terbit IS NULL
            OR tanggal_kedaluwarsa >= tanggal_terbit
        )
);

CREATE INDEX IF NOT EXISTS idx_sertifikat_user_id
    ON sertifikat(user_id);

CREATE INDEX IF NOT EXISTS idx_sertifikat_status_verifikasi
    ON sertifikat(status_verifikasi);

CREATE INDEX IF NOT EXISTS idx_sertifikat_tanggal_terbit
    ON sertifikat(tanggal_terbit);

INSERT INTO schema_migrations (migration)
VALUES ('011_create_sertifikat.sql');

COMMIT;