<?php $base=url('/'); $active='logbook'; $signatures=$week['signatures']??[]; ?>
<!DOCTYPE html><html lang="id">
<?php include __DIR__ . '/../../../../components/dashboard/dosen/Head.php'; ?>
<body class="bg-slate-50 font-[Poppins] text-gray-900 overflow-x-hidden">
<?php include __DIR__ . '/../../../../components/dashboard/dosen/Sidebar.php'; ?><?php include __DIR__ . '/../../../../components/dashboard/dosen/Header.php'; ?>
<main class="min-h-screen pt-20 bg-slate-50 lg:ml-64"><div class="px-4 py-6 mx-auto sm:px-6 sm:py-8 lg:px-8 max-w-6xl">
<a href="<?=e(url('/dashboard/dosen/logbook'))?>" class="text-sm text-blue-600">← Kembali</a><h1 class="mt-3 text-2xl font-bold text-gray-900">Minggu <?=e($week['minggu_ke'])?> · <?=e($week['mahasiswa_nama'])?></h1><p class="mt-1 text-sm text-gray-500"><?=e($week['nim'])?> · <?=e($week['nama_perusahaan'])?> · <?=e(date('d M Y',strtotime($week['tanggal_mulai'])))?> – <?=e(date('d M Y',strtotime($week['tanggal_selesai'])))?></p>
<div class="mt-5 overflow-hidden bg-white border border-gray-100 shadow-sm rounded-2xl"><div class="overflow-x-auto"><table class="w-full min-w-[720px] text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left">Tanggal</th><th class="px-4 py-3 text-left">Masuk</th><th class="px-4 py-3 text-left">Pulang</th><th class="px-4 py-3 text-left">Kegiatan</th><th class="px-4 py-3 text-left">Kehadiran</th></tr></thead><tbody class="divide-y divide-gray-100"><?php foreach($week['daily'] as $day): ?><tr><td class="px-4 py-4"><?=e(date('D, d M Y',strtotime($day['tanggal'])))?></td><td class="px-4 py-4"><?=e($day['jam_masuk']?:'-')?></td><td class="px-4 py-4"><?=e($day['jam_pulang']?:'-')?></td><td class="px-4 py-4 whitespace-pre-line"><?=e($day['kegiatan'])?><?php if($day['status_kehadiran']==='tidak_hadir'): ?><div class="mt-1 text-xs text-amber-700">Alasan: <?=e($day['alasan_ketidakhadiran'])?></div><?php endif;?></td><td class="px-4 py-4"><?=e($day['status_kehadiran']==='hadir'?'Hadir':$day['status_validasi'])?></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="grid grid-cols-1 gap-4 mt-5 sm:grid-cols-3"><?php foreach([['mahasiswa','Mahasiswa'],['mitra','Mitra'],['dosen','Dosen']] as [$stage,$label]): ?><div class="p-4 bg-white border border-gray-100 rounded-2xl"><p class="text-xs font-semibold text-gray-500"><?=e($label)?></p><?php if(!empty($signatures[$stage])):?><img src="<?=e(url('/dashboard/logbook/file/signature/'.(int)$signatures[$stage]['id']))?>" class="object-contain w-full h-20 mt-2 bg-gray-50 rounded-lg" alt="Tanda tangan"><?php else:?><div class="flex items-center justify-center h-20 mt-2 text-xs text-gray-400 bg-gray-50 rounded-lg">Belum</div><?php endif;?></div><?php endforeach;?></div>
<?php if(($week['status']??'')==='menunggu_dosen'): ?><div class="mt-5"><?php $signatureAction=url('/dashboard/dosen/logbook/tanda-tangan/'.(int)$week['id']);$signatureButtonLabel='Tanda Tangani sebagai Dosen';$signatureStageLabel='Tanda Tangan Dosen Pembimbing';include __DIR__.'/../../../../components/dashboard/logbook/SignaturePad.php'; ?></div><?php endif;?>
</div></main></body></html>
